name: Push to Amazon ECR
description: Push to Amazon ECR
inputs:
  AWS_REGION:
    required: false
    default: ap-northeast-2
    description: set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY:
    required: true
    description: set this to your Amazon ECR repository name
  ASSUME_ROLE_PROJECT:
    required: true

outputs:
  image:
    value: ${{ steps.build-image.outputs.image }}
    description: ecr push image

runs:
  using: "composite"
  steps:
    - name: Assume Role for Target Project
      id: assume-role
      run: |
        /bin/bash /opt/github_runner/bin/set_assume_role_cicd.sh ${{ inputs.ASSUME_ROLE_PROJECT }}
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR so that it can be deployed to ECS.
        docker build -t $ECR_REGISTRY/${{ inputs.ECR_REPOSITORY }}:$IMAGE_TAG .
        docker push $ECR_REGISTRY/${{ inputs.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/${{ inputs.ECR_REPOSITORY }}:$IMAGE_TAG"
      shell: bash

